### ISSUE TITLE
Non-python extension dependencies with external dependencies are not recursively patched

### ISSUE THREAD

**Issue by ehashman** [pypa/auditwheel#136] opened 2019-01-24 00:15 UTC
As reported by @thomaslima:

Our wheel has a complicated dependency structure. But the gist of it is the following:

dbcore.so (py_ext) -> lib_tl.so (non-py_ext) -> libcurl.so (external library to be grafted)

Because lib_tl is a non-py extension of dbcore, it was not added to the `full_external_refs` dictionary, which is used by `repair.py` to patch the sonames. So the final result is that lib_tl was not patched, and the package was broken.

See also #134.

**Comment by dsteinmo** [comment] 2019-07-31 14:45
Is there confirmation that the PR proposed by @thomaslima fixes this problem? My project also has a complicated dependency tree, and it would be ideal if all external dependencies that are bundled get patched to include $ORIGIN in rpath. Thanks.

**Comment by grisuthedragon** [comment] 2019-08-29 11:44
We have the same problem that our python extension c_interface.so depends on a library libcode.so which we also ship in the .libs folder. This this is require since the build process of libcode.so does not depend on python and we only create the c_interface.so using setuptools.  libcode.so has all dependencies to the external libaries inside. 

@dsteinmo With the PR #139 integrated in the auditwheel script, the problem is fixed and the wheels work well.

**Comment by dsteinmo** [comment] 2019-08-29 12:32
Sounds good. It does not appear that @thomaslima has engaged the upstream maintainers by rebasing his branch. If I find some time, I'll attempt a fork + new PR.

**Comment by grisuthedragon** [comment] 2019-08-29 12:37
I extracted the crucual part out of @thomaslima  commit, which we use to build our wheels.
[auditwheel.txt](https://github.com/pypa/auditwheel/files/3555540/auditwheel.txt)

**Comment by dsteinmo** [comment] 2019-08-29 12:39
Thanks; I might have spoken too soon, it looks like this is still active, but in a separate branch alongside a separate issue: https://github.com/pypa/auditwheel/pull/134. I'll leave it in the hands of @thomaslima and the maintainers.

**Comment by thomaslima** [comment] 2019-08-29 13:15
Dear all,

I’ve been very busy in the past weeks. I will try to look into this soon. Originally I had one single PR and Elana asked me to split into two. That might have created some confusion. I’ll look into it again about what’s required.

Best,
Thomas

On Aug 29, 2019, at 08:39, Derek Steinmoeller <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks; I might have spoken too soon, it looks like this is still active, but in a separate branch alongside a separate issue: #134<https://github.com/pypa/auditwheel/pull/134>. I'll leave it in the hands of @thomaslima<https://github.com/thomaslima> and the maintainers.

**Comment by delarosatrevin** [comment] 2020-02-17 10:15
Hi everyone, 

Is there any progress on this issue?
I'm facing the same problem to build a wheel for my package **emcore**. 

It is a scientific image processing library that depends on external libraries such as fftw3, libpng, libtiff, and sqlite3 among others. We build libemcore that does not depends on Python and then the Python extension using pybind11. 

Thanks in advance.

**Comment by myselfhimself** [comment] 2020-12-07 18:57
It seems that this command: (relying on the [copydeps](https://pypi.org/project/copydeps/) package)

`copydeps gmic.cpython-37m-x86_64-linux-gnu.so --exclude exclude-list-gmic`

with [exclude-list-gmic's contents here](https://github.com/myselfhimself/gmic-py/issues/82#issuecomment-740065981)

finds and copies files deeper than PR #139 ... Still struggling...

**Comment by myselfhimself** [comment] 2020-12-09 16:48
My copydeps-based script did not work well.

I am giving up on depending on libcurl for linux wheel building and will rely instead of automatic OS execution of the curl executable by the gmic library.

I am getting back to a standard auditwheel version

**Comment by bdice** [comment] 2021-02-03 21:43
This problem is happening for me as well (see issue https://github.com/glotzerlab/freud/issues/720). I have confirmed that PR #139 does solve the problem for our use case. We have a few Python extensions that link to `libfreud.so` and `libtbb.so`. `libfreud.so` is also linked to `libtbb.so`. auditwheel correctly relocates the RPATHs of our Python extensions, but does not relocate the RPATH of `libfreud.so`.

It looks like PR #139 was stalled because the original author needed to update it. I will update it and file a new PR so that this can hopefully be fixed in the next release of auditwheel.

**Comment by thomaslima** [comment] 2021-02-03 22:17
I’m very sorry I haven’t had the time to review the updates on the PR and issues. Thank you for working on this.

**Comment by bdice** [comment] 2021-02-03 23:15
@thomaslima No problem! Thanks for your initial work on it. I am updating the tests, too. PR #134 with the corresponding tests was reverted in #190, so I will try to improve it according to the maintainers’ comments on why it was reverted.

**Comment by bdice** [comment] 2021-02-06 23:56
@thomaslima I created a new pull request https://github.com/pypa/auditwheel/pull/283 to solve this issue, based on your previous work. Thanks for your initial efforts in #139, it just took a little bit of cleanup and updating tests! 👍 🚀

**Comment by molpopgen** [comment] 2021-03-08 15:46
Am I mistaken, or is this a duplicate of #48?  Came across both after running into this issue myself.

**Closed** 2021-03-18 18:09 UTC
Labels: bug, has PR
