### ISSUE TITLE
Why the return value is still 0 when the package  is not compatible with manylinux1

### ISSUE THREAD

**Issue by JasonChen233** [pypa/auditwheel#318] opened 2021-08-12 06:49 UTC
`xxx@nxxx-xxx-xxx:~/pythonProject/test$ auditwheel show bytedxxx-0.0.1-cp27-cp27mu-linux_x86_64.whl

bytedxxx-0.0.1-cp27-cp27mu-linux_x86_64.whl is consistent with
the following platform tag: "linux_x86_64".

This wheel uses the PyFPE_jbuf function, which is not compatible with
the manylinux1 tag. (see
https://www.python.org/dev/peps/pep-0513/#fpectl-builds-vs-no-fpectl-builds)
xxx@nxxx-xxx-xxx:~/pythonProject/test$ echo $?
0`
I want to use auditwheel to check some package and get the result by return value.And expect to get a not 0 return value here.How can I  judge whether the pacakge passed the examination?

**Comment by mayeut** [comment] 2021-10-03 11:13
Duplicate of #180

**Closed by mayeut** 2021-10-03 11:13 UTC
