### ISSUE TITLE
Python C++ module not properly repaired, retains dependency on symlink to bundled library

### ISSUE THREAD

**Issue by madig** [pypa/auditwheel#159] opened 2019-05-04 12:21 UTC
I have a Python C++ module that links to libcrypto from OpenSSL and libcurl. I build the package on the manylinux2010 container (`python3 setup.py bdist_wheel`) and run `auditwheel repair` on the .whl. The library shared objects (libcrypto, libz and libcurl) are correctly packed in and ldd-ing the Python module shared object correctly finds and shows them as dependencies, yet it retains a dependency on "libcrypto.so.10", which is named differently on e.g. Debian-based containers, making import fail. What am I missing?

**Comment by madig** [comment] 2019-05-06 09:56
Ugh. I can't even run the resulting wheel on the manylinux2010 container, same eror:

```
ImportError: /tmp/venv/lib/python3.7/site-packages/dsign/.libs/libcrypto-a94305d7.so.1.0.1e: version `libcrypto.so.10' not found (required by /tmp/venv/lib/python3.7/site-packages/dsign/_dsign.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by madig** [comment] 2019-05-06 10:44
I tried linking the library to libcrypto statically and it works, but:
```
(venv) [root@a381fbecf6ea dsign]# auditwheel show dist/dsign-1.4.5.dev0+gf7b8133.d20190506-cp37-cp37m-linux_x86_64.whl

dsign-1.4.5.dev0+gf7b8133.d20190506-cp37-cp37m-linux_x86_64.whl is
consistent with the following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libgcc_s.so.1 with versions {'GCC_3.0'},
libpthread.so.0 with versions {'GLIBC_2.2.5'}, libc.so.6 with versions
{'GLIBC_2.3.4', 'GLIBC_2.7', 'GLIBC_2.4', 'GLIBC_2.3', 'GLIBC_2.2.5'},
libstdc++.so.6 with versions {'CXXABI_1.3', 'GLIBCXX_3.4'}

This constrains the platform tag to "manylinux2010_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```
```
(venv) [root@a381fbecf6ea dsign]# auditwheel repair dist/dsign-1.4.5.dev0+gf7b8133.d20190506-cp37-cp37m-linux_x86_64.whl
INFO:auditwheel.main_repair:Repairing dsign-1.4.5.dev0+gf7b8133.d20190506-cp37-cp37m-linux_x86_64.whl
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "dist/dsign-1.4.5.dev0+gf7b8133.d20190506-cp37-cp37m-linux_x86_64.whl" to "manylinux1_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
```
Wat.

**Comment by lkollar** [comment] 2019-05-08 15:00
Could you upload the wheel somewhere? If possible the original version before you ran `repair` on it.

**Comment by madig** [comment] 2019-05-13 07:40
(Sorry for the late reply, I can't share that wheel but will do a minimal example when I get the time...)

**Comment by bakatrouble** [comment] 2019-05-14 02:07
@lkollar 
I have a "repaired" wheel here: https://files.pythonhosted.org/packages/8a/12/9db1f67e2747c32491edbfaccd00e8c6379dba2589da0ba22ff4ec747c19/pytgvoip-0.0.2.3-cp37-cp37m-manylinux2010_x86_64.whl

**Comment by bakatrouble** [comment] 2019-05-14 02:34
https://drop.bakatrouble.me/pytgvoip.whl/
Here are newly built non-repaired and repaired wheels

**Comment by lkollar** [comment] 2019-05-14 05:58
Thanks, I’ll try to have a look later this week.

**Comment by lkollar** [comment] 2019-05-15 08:21
I think this is due to a `patchelf` bug @njsmith has already reported and fixed in https://github.com/NixOS/patchelf/issues/84 but hasn't been released. `patchelf` does not update the `.gnu_version_r` section with the vendored library so the linker rejects our `.so` as it thinks it's not the correct version:

```      386:	/tmp/voip/lib/python3.7/site-packages/.libs_tgvoip/libcrypto-a94305d7.so.1.0.1e: error: version lookup error: version `libcrypto.so.10' not found (required by /tmp/voip/lib/python3.7/site-packages/.libs_tgvoip/libtgvoip-d66a5fc7.so.0.0.0) (fatal)```

Relevant `.gnu_version_r` section in `.libs_tgvoip/libtgvoip-d66a5fc7.so.0.0.0`:
```
0x0030: Version: 1  File: libcrypto-a94305d7.so.1.0.1e  Cnt: 1
 0x0040:   Name: libcrypto.so.10  Flags: none  Version: 8
```

I'll try to confirm with the patched `patchelf` version.

**Comment by lkollar** [comment] 2019-05-15 08:23
Small correction: there is a `patchelf` release which should contain the fix: 0.10. I had 0.9 installed while I was testing this. Will check with 0.10.

**Comment by lkollar** [comment] 2019-05-15 19:57
The version information appears to be correct after installing `patchelf` 0.10 and running `auditwheel repair`. I can't produce a `libtgvoip.so` version which would have matching symbols needed by the wheel attached by @bakatrouble though. Can you try to repair the wheel again with the newer `patchelf`?

I think we should add a version check on `patchelf` 0.10 and display a warning if users attempt to repair wheels with lower versions.

**Comment by bakatrouble** [comment] 2019-05-15 23:16
![image](https://user-images.githubusercontent.com/7340354/57815328-a9830a00-777f-11e9-9946-5f54631fccb6.png)
Same error when importing extension (`version ``libcrypto.so.10' not found`), no 
Added v0.0.2.7 wheels at the same location: https://drop.bakatrouble.me/pytgvoip.whl/

If it'll help, Dockerfile used for building is [here](https://gist.github.com/71c2e36d9d07c67a03dde93a58c3bed7).
Run using `docker run -iv ${PWD}/dist:/dist $IMAGEID`, source and repaired wheels will output to the `dist` directory

**Comment by bakatrouble** [comment] 2019-05-15 23:26
![image](https://user-images.githubusercontent.com/7340354/57815903-05e72900-7782-11e9-8409-fe8957b4d04b.png)
Here's the output of `auditwheel show`

**Comment by bakatrouble** [comment] 2019-05-15 23:33
[Here](https://gist.github.com/bakatrouble/6027c8ea10794d6f25dc31fe558c53bd)'s the output of `auditwheel lddtree` for the extension `.so` and `libtgvoip.so.0.0.0`

**Comment by lkollar** [comment] 2019-05-16 08:17
Thanks for the Dockerfile. I can confirm that even with `patchelf 0.10` the resulting .so file does not appear to have the correct version information:

```
  0x0030: Version: 1  File: libcrypto-a94305d7.so.1.0.1e  Cnt: 1
  0x0040:   Name: libcrypto.so.10  Flags: none  Version: 8
```

This needs more investigation.

**Comment by lkollar** [comment] 2019-05-28 21:26
The above version information is actually correct. This particular version of`libcrypto.so` uses the `libcrypto.so.10` version string on its exported symbols. The `.gnu.version_d` section in the original .so displays the correct version strings:

```
Version definition section '.gnu.version_d' contains 4 entries:
  Addr: 0x00000000000371d8  Offset: 0x0371d8  Link: 4 (.dynstr)
  000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: libcrypto.so.10
  0x0014: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: libcrypto.so.10
  0x0030: Rev: 1  Flags: none  Index: 3  Cnt: 1  Name: OPENSSL_1.0.1
  0x004c: Rev: 1  Flags: none  Index: 4  Cnt: 1  Name: OPENSSL_1.0.1_EC
```

However, the vendored .so has incorrect version information in this section:

```
Version definition section '.gnu.version_d' contains 4 entries:
  Addr: 0x00000000000371d8  Offset: 0x0371d8  Link: 27 (.dynstr)
  000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: XXXXXXXXXXXXXXX
  0x0014: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: XXXXXXXXXXXXXXX
  0x0030: Rev: 1  Flags: none  Index: 3  Cnt: 1  Name: OPENSSL_1.0.1
  0x004c: Rev: 1  Flags: none  Index: 4  Cnt: 1  Name: OPENSSL_1.0.1_E
```

This happens because `patchelf` replaces the original `DT_SONAME` entry in `.dynstr` with a "XXXXXXXXXXXXXXX" string. Since the `.gnu.version_r` section in `libcrypto.so` still points to the index of the original entry in `.dynstr` now the required version is "XXXXXXXXXXXXXXX".

Version strings in the dnyamic string table:

`readelf -p .dynstr libcrypto-a94305d7.so.1.0.1e`

```
  [ 1327f]  XXXXXXXXXXXXXXX
  [ 1328f]  OPENSSL_1.0.1
  [ 1329d]  OPENSSL_1.0.1_EC
  [ 132ae]  GLIBC_2.2.5
  [ 132ba]  GLIBC_2.4
  [ 132c4]  GLIBC_2.3
  [ 132ce]  GLIBC_2.7
  [ 132d8]  GLIBC_2.3.4
  [ 132e4]  libcrypto-a94305d7.so.1.0.1e
  [ 13301]  libz-eb09ad1d.so.1.2.3
  ```

The new `SONAME` is added to the end as a new value and the original version is "zeroed out". Unofortunately in the case of `libcrypto.so`, this string is used as the exported version as well.

The original `.dynstr` section for reference:

`readelf -p .dynstr /usr/lib64/libcrypto.so`
```
  [ 1327f]  libcrypto.so.10
  [ 1328f]  OPENSSL_1.0.1
  [ 1329d]  OPENSSL_1.0.1_EC
  [ 132ae]  GLIBC_2.2.5
  [ 132ba]  GLIBC_2.4
  [ 132c4]  GLIBC_2.3
  [ 132ce]  GLIBC_2.7
  [ 132d8]  GLIBC_2.3.4
```

The code to zero out the original `SONAME` in `patchelf` is here: https://github.com/NixOS/patchelf/blob/1c95784c028d214c475d4f34ea6c3faabb5765ce/src/patchelf.cc#L1077-L1082. I will file an issue to better understand why this is necessary and maybe remove it. I don't see other options at the moment to work around this issue.

**Comment by lkollar** [comment] 2019-05-28 21:28
This has already been reported in `patchelf`: https://github.com/NixOS/patchelf/issues/155.

**Comment by jfolz** [comment] 2020-01-31 08:49
Has there been any movement on this? As far as I can tell the only way to publish wheels that require, e.g. CUDA, is to lie about them being manylinux.

**Comment by lkollar** [comment] 2020-02-04 09:20
There has been no movement on applying the fix in patchelf. We could apply the patch in the version of patchelf we ship with the manylinux images as a workaround though.

**Comment by jfolz** [comment] 2020-02-07 09:34
That might be necessary, though the current situation is overall undesirable.
I ran into strange issues recently that I tracked down to Pytorch from PyPI loading its own version of the CUDA runtime, which was different from the system version. My extension was built again the system CUDA and they were interfering with each other. Basically, my code would change some global state (probably the CUDA context) that confused Pytorch and it crashed profusely.

**Comment by jfolz** [comment] 2020-02-07 09:39
What I mean by this is: I would very much like to publish wheels to PyPI, but I doubt it would bring any good. Since my package is meant to interact closely with Pytorch and other similar frameworks, there are bound to be issues where users update either package, resulting in such a version mismatch with dependencies. So, I don't know if publishing manylinux wheels is useful at all without users knowing exactly what's going on in the background.

**Closed** 2020-04-24 10:16 UTC

**Comment by jfolz** [comment] 2020-04-28 15:18
Can confirm that pypa/manylinux#545 fixes auditwheel with CUDA libraries. Thanks a bunch!
